# Generated by Django 4.0.6 on 2022-07-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('english', models.CharField(max_length=20)),
                ('hindi', models.CharField(max_length=20)),
                ('math', models.CharField(max_length=20)),
                ('science', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '12 Class Students',
            },
        ),
    ]
