# Generated by Django 4.0.6 on 2022-07-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentfive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('History', models.CharField(max_length=20)),
                ('hindi', models.CharField(max_length=20)),
                ('Sociology', models.CharField(max_length=20)),
                ('Economics', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '12 Class Arts',
            },
        ),
        migrations.CreateModel(
            name='Studentfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('History', models.CharField(max_length=20)),
                ('hindi', models.CharField(max_length=20)),
                ('Sociology', models.CharField(max_length=20)),
                ('Economics', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '12 Class Arts',
            },
        ),
        migrations.CreateModel(
            name='Studentone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('Physics', models.CharField(max_length=20)),
                ('Chemistry', models.CharField(max_length=20)),
                ('Biology', models.CharField(max_length=20)),
                ('Mathematics', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '11 Class Science',
            },
        ),
        migrations.CreateModel(
            name='Studentthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('Accountancy', models.CharField(max_length=20)),
                ('Business', models.CharField(max_length=20)),
                ('Economics', models.CharField(max_length=20)),
                ('English', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '11 Class Commerce',
            },
        ),
        migrations.CreateModel(
            name='Studenttwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('Accountancy', models.CharField(max_length=20)),
                ('Business', models.CharField(max_length=20)),
                ('Economics', models.CharField(max_length=20)),
                ('English', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '12 Class Commerce',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '12 Class Science'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='english',
            new_name='Biology',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='math',
            new_name='Chemistry',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='hindi',
            new_name='Mathematics',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='science',
            new_name='Physics',
        ),
    ]
