# Generated by Django 4.0.6 on 2022-07-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_studentfive_studentfour_studentone_studentthree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfive',
            options={'verbose_name_plural': '1 Class Arts'},
        ),
    ]
