# Generated by Django 4.0.6 on 2022-07-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_studentfive_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentone',
            old_name='Chemistry',
            new_name='ChemistryChemistry',
        ),
    ]
