# Generated by Django 4.0.6 on 2022-07-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_chemistry_studentone_chemistrychemistry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfive',
            options={'verbose_name_plural': '11 Class Arts'},
        ),
    ]
