# Generated by Django 4.0.6 on 2022-07-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_name_name_alter_studentfive_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfive',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
