# Generated by Django 4.0.6 on 2022-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_studentfive_name_delete_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentone',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
